// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXuVMxHaGafi9PdvyyrjQ_TdpixoXxeU',
    appId: '1:226161194431:web:666c25499e8ea63c8bdd0a',
    messagingSenderId: '226161194431',
    projectId: 'gamezone-10237',
    authDomain: 'gamezone-10237.firebaseapp.com',
    storageBucket: 'gamezone-10237.appspot.com', 
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVG-ib1Bw793glUF2ja1iEP9Kh0L6ydQ',
    appId: '1:226161194431:android:75c1ec8fc9f4c5838bdd0a',
    messagingSenderId: '226161194431',
    projectId: 'gamezone-10237',
    storageBucket: 'gamezone-10237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhiryXWYcbp7mj0sJK0BN4y_jLoKfNBkE',
    appId: '1:226161194431:ios:5ddda8edf1a5a0f88bdd0a',
    messagingSenderId: '226161194431',
    projectId: 'gamezone-10237',
    storageBucket: 'gamezone-10237.appspot.com',
    iosBundleId: 'com.example.flutterloginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhiryXWYcbp7mj0sJK0BN4y_jLoKfNBkE',
    appId: '1:226161194431:ios:a77986000d802c148bdd0a',
    messagingSenderId: '226161194431',
    projectId: 'gamezone-10237',
    storageBucket: 'gamezone-10237.appspot.com',
    iosBundleId: 'com.example.flutterloginSignup.RunnerTests',
  );
}
